name: build
on:
  push:
  pull_request:
  # build weekly at 4:00 AM UTC
  schedule:
    - cron: '0 4 * * 1'

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: "lint on ${{ matrix.os }} "
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install tox
        run: python -m pip install -U tox
      - name: run mypy
        run: tox -e mypy

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        # we do not want a large number of windows and macos builds, so
        # enumerate them explicitly
        include:
          - os: windows-latest
            python-version: "3.10"
          - os: macos-latest
            python-version: "3.10"
    name: "test py${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install tox
        run: python -m pip install -U tox
      - name: run tests
        run: python -m tox -e py

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install tox
        run: python -m pip install -U tox
      - name: test reference docs generation
        run: python -m tox -e reference

  test-package-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: install tox
        run: python -m pip install -U tox
      - name: check package metadata
        run: python -m tox -e twine-check

  test-mindeps:
    runs-on: ubuntu-latest
    name: "mindeps"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: install tox
        run: python -m pip install -U tox
      - name: test
        run: tox -e py-mindeps

  test-sdk-main:
    strategy:
      matrix:
        python-version: ["3.6", "3.10"]
    runs-on: ubuntu-latest
    name: "sdk-main"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -U tox
      - run: tox -e py-sdkmain

  # use the oldest python version we support for this build
  test-ancient-virtualenv:
    name: "test on py3.6, using old virtualenv"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Requirements
        run: python -m pip install -U pip setuptools tox
      - name: Downgrade Virtualenv
        run: python -m pip install 'virtualenv==16.7.12'
      - name: Run Tests
        run: python -m tox -e py
